name: spotnsend
description: SpotnSend mobile front-end app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^16.2.2
  flutter_riverpod: ^3.0.0
  permission_handler: ^12.0.1
  location: ^8.0.1
  image_picker: ^1.0.7
  file_picker: ^10.3.3
  google_fonts: ^6.2.1
  maplibre_gl: ^0.22.0
  intl: ^0.20.2
  collection: ^1.18.0
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.5.6
  qr_flutter: ^4.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.2
  http: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - fixtures/
    - .env
    - assets/category_icons/
    - assets/pins/
    - assets/logo/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_spotnsend.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/logo_spotnsend.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/logo_spotnsend.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/logo_spotnsend.png"
