name: spotnsend
description: SpotnSend mobile front-end app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^16.2.2
  flutter_riverpod: ^3.0.0
  permission_handler: ^12.0.1
  location: ^8.0.1
  dio: ^5.4.2+1
  image_picker: ^1.0.7
  file_picker: ^10.3.3
  google_fonts: ^6.2.1
  maplibre_gl: ^0.22.0
  intl: ^0.20.2
  collection: ^1.18.0
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - fixtures/
    - .env
